<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Variables -->
  <xacro:property name="base_length" value="0.498"/>
  <xacro:property name="base_width" value="0.4"/>
  <xacro:property name="base_height" value="0.02"/>
  <xacro:property name="top_length" value="0.246"/>
  <xacro:property name="top_width" value="0.361"/>
  <xacro:property name="top_height" value="0.03"/>
  <xacro:property name="clearance" value="0.05"/>

  <!-- Base Link -->
  <link name="base_link"/>

  <!-- Base Plate -->
  <joint name="base_joint" type="fixed">
    <origin xyz="0.0 0.0 ${clearance + base_height + 0.01}"/>  <!-- 1cm provided for no clipping -->
    <parent link="base_link"/>
    <child link="base_plate"/>
  </joint>

  <link name="base_plate">
    <inertial>
      <origin xyz="0.0 0.0 -${base_height/2}"/>
      <mass value="0.0"/>
      <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
    <visual>
      <origin xyz="0.0 0.0 -${base_height/2}"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 -${base_height/2}"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="1.0" x="${base_length}" y="${base_width}" z="${base_height}">
      <origin xyz="0.0 0.0 -${base_height/2}"/>
    </xacro:inertial_box>
  </link>

  <!-- Top Plate -->
  <!-- <joint name="top_joint" type="fixed">
    <origin xyz="-${base_length/2 - top_length/2} ${base_width/2 - top_width/2} ${top_height}"/>
    <parent link="base_plate"/>
    <child link="top_plate"/>
  </joint>

  <link name="top_plate">
    <inertial>
      <origin xyz="0.0 0.0 -${top_height/2}"/>
      <mass value="0.0"/>
      <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
    <visual name="">
      <origin xyz="0.0 0.0 -${top_height/2}"/>
      <geometry>
        <box size="${top_length} ${top_width} ${top_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 1.0 1.0"/>
        <texture filename=""/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 -${top_height/2}"/>
      <geometry>
        <box size="${top_length} ${top_width} ${top_height}"/>
      </geometry>
    </collision>
  </link> -->

</robot>
