<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Variables -->
  <xacro:property name="lidar_height" value="0.042" />
  <xacro:property name="lidar_radius" value="0.036" />

  <!-- Links -->
  <joint name="lidar_joint" type="fixed">
    <origin xyz="0 0 ${lidar_height/2}"/>
    <parent link="top_plate"/>
    <child link="lidar_link"/>
  </joint>

  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder length="${lidar_height}" radius="${lidar_radius}"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder length="${lidar_height}" radius="${lidar_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
  </link>
  <gazebo reference="lidar_link">
    <material>Gazebo/Red</material>
    <sensor type="ray" name="lidar_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-${pi}</min_angle>
            <max_angle>${pi}</max_angle>
          </horizontal>
          <range>
            <min>0.12</min>
            <max>6</max>
          </range>
        </scan>
        <range>
          <min>0.3</min>
          <max>12</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_lidar" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <argument> ~/out:=scan </argument>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>lidar_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>
</robot>
