<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Variables -->
  <xacro:property name="base_length" value="0.372" />
  <xacro:property name="base_width" value="0.361" />
  <xacro:property name="wheel_radius" value="0.035" />
  <xacro:property name="wheel_width" value="0.04" />
  <xacro:property name="wheel_gap" value="0.01" />

  <!-- Wheel Macro -->
  <xacro:macro name="wheel" params="prefix parent x y z z_sign">
    <joint name="${prefix}_joint" type="continuous">
      <parent link="${parent}"></parent>
      <child link="${prefix}_wheel"></child>
      <origin xyz="${x} ${y} ${z}" rpy="${z_sign * pi/2} 0 0" />
      <axis xyz="0 0 ${-1 * z_sign}" />
    </joint>

    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    <inertial>
      <origin xyz="0 0 ${wheel_radius}"/>
      <mass value="1"/>
      <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
    </link> 
  </xacro:macro>

  <!-- Wheels -->
  <xacro:wheel prefix="top_left" parent="base_plate" x="${base_width/2 - 0.03}" y="${base_length/2 + wheel_gap + wheel_width/2}" z="-0.04" z_sign="1"/>
  <xacro:wheel prefix="top_right" parent="base_plate" x="${base_width/2 - 0.03}" y="-${base_length/2 + wheel_gap + wheel_width/2}" z="-0.04" z_sign="1"/>
  <xacro:wheel prefix="bottom_left" parent="base_plate" x="-${base_width/2 - 0.03}" y="${base_length/2 + wheel_gap + wheel_width/2}" z="-0.04" z_sign="-1"/>
  <xacro:wheel prefix="bottom_right" parent="base_plate" x="-${base_width/2 - 0.03}" y="-${base_length/2 + wheel_gap + wheel_width/2}" z="-0.04" z_sign="-1"/>
</robot>
